//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public string itemID { get; set; }
        public string description { get; set; }
        public float weight { get; set; }
        public float length { get; set; }
        public float width { get; set; }
        public float height { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual ICollection<orderdetail> orderdetails { get; set; }
    }
}
