//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edeEntities : DbContext
    {
        public edeEntities()
            : base("name=edeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<airwaybill> airwaybills { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<office> offices { get; set; }
        public DbSet<orderdetail> orderdetails { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<pickup> pickups { get; set; }
        public DbSet<staff> staffs { get; set; }
        public DbSet<fee> fees { get; set; }
        public DbSet<shipment> shipments { get; set; }
    }
}
