//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class pickup
    {
        public int pickupID { get; set; }
        public System.DateTime pickupDate { get; set; }
        public sbyte services { get; set; }
        public int pickup_cusID { get; set; }
        public string pickup_address { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
