//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        public int shipmentID { get; set; }
        public string destination { get; set; }
        public System.DateTime sendDate { get; set; }
        public int itemCount { get; set; }
        public string vehicleNo { get; set; }
        public sbyte shipmentType { get; set; }
        public string currentLoc { get; set; }
        public int shipment_AirwayBillID { get; set; }
    
        public virtual airwaybill airwaybill { get; set; }
    }
}
