//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipment
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.customers = new HashSet<customer>();
            this.staff1 = new HashSet<staff>();
        }
    
        public int staffNo { get; set; }
        public string staffPwd { get; set; }
        public string staffName { get; set; }
        public string extension { get; set; }
        public string email { get; set; }
        public Nullable<sbyte> isActive { get; set; }
        public float salary { get; set; }
        public Nullable<int> reportsTo { get; set; }
        public string jobTitle { get; set; }
        public Nullable<System.DateTime> dateOfEmployment { get; set; }
        public Nullable<System.DateTime> dateOfResignation { get; set; }
        public string officeCode { get; set; }
        public sbyte staffType { get; set; }
        public sbyte staffDept { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
        public virtual office office { get; set; }
        public virtual ICollection<staff> staff1 { get; set; }
        public virtual staff staff2 { get; set; }
    }
}
