//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipmentCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class airwaybill
    {
        public airwaybill()
        {
            this.orderdetails = new HashSet<orderdetail>();
            this.payments = new HashSet<payment>();
            this.shipments = new HashSet<shipment>();
        }
    
        public int airwayBillID { get; set; }
        public int services { get; set; }
        public int destinationCountry { get; set; }
        public string deliveryAddress { get; set; }
        public string postCode { get; set; }
        public string receiverCompany { get; set; }
        public string receiverName { get; set; }
        public string receiverPhone { get; set; }
        public string receiverEmail { get; set; }
        public float declaredValue { get; set; }
        public string contentDescription { get; set; }
        public float weight { get; set; }
        public float length { get; set; }
        public float width { get; set; }
        public float height { get; set; }
        public System.DateTime date { get; set; }
        public int status { get; set; }
        public string statusComment { get; set; }
        public int cusID { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<shipment> shipments { get; set; }
    }
}
