//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipmentCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.airwaybills = new HashSet<airwaybill>();
            this.payments = new HashSet<payment>();
            this.pickups = new HashSet<pickup>();
        }
    
        public int cusID { get; set; }
        public string cusPassword { get; set; }
        public string cusName { get; set; }
        public string cusPhone { get; set; }
        public string cusAddress { get; set; }
        public string cusEmail { get; set; }
        public bool isActive { get; set; }
        public bool cusType { get; set; }
        public Nullable<double> creditLimit { get; set; }
        public bool ccType { get; set; }
        public string ccNo { get; set; }
        public string ccExpiry { get; set; }
        public Nullable<int> salesRepEmployeeNumber { get; set; }
    
        public virtual ICollection<airwaybill> airwaybills { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<payment> payments { get; set; }
        public virtual ICollection<pickup> pickups { get; set; }
    }
}
