//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessShipmentCustomer
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public int feeID { get; set; }
        public sbyte feeType { get; set; }
        public float fee1 { get; set; }
    }
}
